version: '3.9'

services:

  flask:
    build: ./app
    container_name: flask-app
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    env_file:
      - ./app/configs.env
    command: gunicorn main:app --bind 0.0.0.0:5000 --reload